/**
 * Demo medicine seed script.
 * Run from the server directory:
 *   node seed.js
 */
import dotenv from "dotenv";
import mongoose from "mongoose";
import Medicine from "./models/medicines.js";

dotenv.config();

const MEDICINES = [
  // ── Prescription Required ─────────────────────────────────
  {
    name: "Botox (Botulinum Toxin Type A) 100 Units",
    brand: "Allergan",
    category: "Botulinum Toxins",
    description: "Botulinum Toxin Type A 100U vial. Indicated for glabellar lines, crow's feet, and forehead wrinkles.",
    howToUse: "Reconstitute with 2.5ml saline. Inject intramuscularly at approved sites. Dosing varies by indication.",
    safetyInfo: "For professional use only. Contraindicated in pregnancy and neuromuscular junction disorders.",
    prescriptionRequired: true,
    prescriptionType: "required",
    buyingPrice: 65,
    sellingPrice: 120,
    price: 120,
    unitPrice: 120,
    stock: 50,
    sku: "BOT-ALL-100",
    supplier: "Allergan Ltd",
    dispensedBy: "Registered Prescriber",
    sideEffects: ["Bruising", "Headache", "Ptosis (rare)", "Localised pain"],
  },
  {
    name: "Dysport 500 Units",
    brand: "Ipsen",
    category: "Botulinum Toxins",
    description: "AbobotulinumtoxinA 500 Unit vial. Used for aesthetic and therapeutic indications.",
    howToUse: "Dilute to desired concentration. Inject into target muscles as directed.",
    safetyInfo: "Units are not interchangeable with other botulinum toxin products.",
    prescriptionRequired: true,
    prescriptionType: "required",
    buyingPrice: 80,
    sellingPrice: 145,
    price: 145,
    unitPrice: 145,
    stock: 30,
    sku: "DYS-IPS-500",
    supplier: "Ipsen Ltd",
    dispensedBy: "Registered Prescriber",
    sideEffects: ["Injection site pain", "Headache", "Nausea"],
  },
  {
    name: "Juvederm Ultra Plus XC 1ml",
    brand: "Allergan",
    category: "Dermal Fillers",
    description: "Cross-linked hyaluronic acid dermal filler with lidocaine for deep tissue augmentation.",
    howToUse: "Inject into the deep dermis or subcutaneous layer. Use appropriate needle or cannula.",
    safetyInfo: "Avoid areas with active infection. Do not use with permanent implants. Vascular occlusion risk — ensure aspiration.",
    prescriptionRequired: true,
    prescriptionType: "required",
    buyingPrice: 60,
    sellingPrice: 110,
    price: 110,
    unitPrice: 110,
    stock: 60,
    sku: "JUV-ULT-1ML",
    supplier: "Allergan Ltd",
    dispensedBy: "Registered Prescriber",
    sideEffects: ["Swelling", "Bruising", "Redness", "Vascular occlusion (rare)"],
  },
  {
    name: "Restylane Lyft 1ml",
    brand: "Galderma",
    category: "Dermal Fillers",
    description: "Stabilised hyaluronic acid gel for cheek augmentation and mid-face volume.",
    howToUse: "Inject into the subcutaneous layer or supra-periosteal plane. Massage after injection if required.",
    safetyInfo: "For experienced injectors only. Perform vascular assessment before injecting.",
    prescriptionRequired: true,
    prescriptionType: "required",
    buyingPrice: 55,
    sellingPrice: 100,
    price: 100,
    unitPrice: 100,
    stock: 45,
    sku: "REST-LYF-1ML",
    supplier: "Galderma UK",
    dispensedBy: "Registered Prescriber",
    sideEffects: ["Bruising", "Swelling", "Tenderness"],
  },
  {
    name: "Sculptra (Poly-L-Lactic Acid) 2 Vials",
    brand: "Galderma",
    category: "Dermal Fillers",
    description: "PLLA bio-stimulator for gradual volume restoration and collagen induction.",
    howToUse: "Reconstitute with 5-8ml sterile water 24h before use. Inject deep dermis/subcutaneous tissue.",
    safetyInfo: "Not for lip augmentation. Avoid intra-vascular injection. Massage 5-5-5 protocol post treatment.",
    prescriptionRequired: true,
    prescriptionType: "required",
    buyingPrice: 150,
    sellingPrice: 280,
    price: 280,
    unitPrice: 280,
    stock: 20,
    sku: "SCULP-2VL",
    supplier: "Galderma UK",
    dispensedBy: "Registered Prescriber",
    sideEffects: ["Nodules (if not massaged)", "Bruising", "Delayed swelling"],
  },
  {
    name: "Aqualyx Fat Dissolving 8ml",
    brand: "Marllor International",
    category: "Fat Dissolvers",
    description: "Phosphatidylcholine-based injectable for localised fat reduction (submental, jowls, body).",
    howToUse: "Inject intra-adipose. 2-8ml per treatment site. May require multiple sessions.",
    safetyInfo: "Do not inject intravascularly. Swelling expected up to 2 weeks. Contraindicated in pregnancy.",
    prescriptionRequired: true,
    prescriptionType: "required",
    buyingPrice: 20,
    sellingPrice: 45,
    price: 45,
    unitPrice: 45,
    stock: 80,
    sku: "AQUA-8ML",
    supplier: "Marllor International",
    dispensedBy: "Registered Prescriber",
    sideEffects: ["Swelling", "Redness", "Bruising", "Numbness"],
  },
  {
    name: "Profhilo 2ml Skin Booster",
    brand: "IBSA",
    category: "Skin Boosters",
    description: "High-concentration unstabilised HA bio-remodeller for skin laxity and hydration.",
    howToUse: "BAP technique — 5 injection points per side of face. Two sessions 4 weeks apart.",
    safetyInfo: "Not a filler. Avoid areas of active infection or inflammation.",
    prescriptionRequired: false,
    prescriptionType: "none",
    buyingPrice: 90,
    sellingPrice: 160,
    price: 160,
    unitPrice: 160,
    stock: 40,
    sku: "PROF-2ML",
    supplier: "IBSA Pharma",
    dispensedBy: "Trained Aesthetic Professional",
    sideEffects: ["Mild swelling", "Bruising", "Temporary lumpiness"],
  },

  // ── No Prescription Required ──────────────────────────────
  {
    name: "Sunekos 1200 Skin Booster 1ml",
    brand: "Professional Derma",
    category: "Skin Boosters",
    description: "Patented formula of amino acids and HA for dermal regeneration and elastin stimulation.",
    howToUse: "Inject intradermally. Typical protocol: 4 sessions every 7 days.",
    safetyInfo: "Avoid eyes and mucous membranes. Patch test not required.",
    prescriptionRequired: false,
    prescriptionType: "none",
    buyingPrice: 40,
    sellingPrice: 75,
    price: 75,
    unitPrice: 75,
    stock: 55,
    sku: "SUNE-1200",
    supplier: "Professional Derma",
    dispensedBy: "Aesthetic Professional",
    sideEffects: ["Mild redness", "Swelling at injection site"],
  },
  {
    name: "Lemon Bottle Fat Dissolve 10ml",
    brand: "Lemon Bottle",
    category: "Fat Dissolvers",
    description: "Premium premium fat dissolving solution with riboflavin, bromelain, and lecithin.",
    howToUse: "Inject mesodermally into fat deposits. 2-4 sessions recommended 2 weeks apart.",
    safetyInfo: "Avoid in diabetics without medical supervision. Keep area clean post treatment.",
    prescriptionRequired: false,
    prescriptionType: "none",
    buyingPrice: 15,
    sellingPrice: 35,
    price: 35,
    unitPrice: 35,
    stock: 100,
    sku: "LEM-10ML",
    supplier: "Lemon Bottle UK",
    dispensedBy: "Aesthetic Professional",
    sideEffects: ["Swelling", "Bruising", "Itching"],
  },
  {
    name: "Mesotherapy Cocktail (Hair) 5ml",
    brand: "Meso Pharma",
    category: "Mesotherapy",
    description: "Vitamin-mineral complex with biotin, zinc, and growth factors for hair loss treatment.",
    howToUse: "Inject intradermally into scalp. 1ml per session, 4-8 sessions.",
    safetyInfo: "Not suitable for alopecia areata without dermatologist assessment.",
    prescriptionRequired: false,
    prescriptionType: "none",
    buyingPrice: 18,
    sellingPrice: 40,
    price: 40,
    unitPrice: 40,
    stock: 70,
    sku: "MESO-HAIR-5ML",
    supplier: "Meso Pharma",
    dispensedBy: "Aesthetic Professional",
    sideEffects: ["Scalp tenderness", "Mild flaking"],
  },
  {
    name: "EMLA Cream 5% 30g",
    brand: "AstraZeneca",
    category: "Anesthetics",
    description: "Topical eutectic mixture of lidocaine 2.5% and prilocaine 2.5% for skin numbing.",
    howToUse: "Apply 1-2g per 10cm² under occlusive dressing 1 hour before procedure.",
    safetyInfo: "Avoid mucous membranes. Max 60g per application in adults.",
    prescriptionRequired: false,
    prescriptionType: "optional",
    buyingPrice: 8,
    sellingPrice: 18,
    price: 18,
    unitPrice: 18,
    stock: 120,
    sku: "EMLA-30G",
    supplier: "AstraZeneca",
    dispensedBy: "Any Professional",
    sideEffects: ["Blanching", "Erythema", "Edema"],
  },
  {
    name: "Yvoire Classic 1ml Dermal Filler",
    brand: "LG Life Sciences",
    category: "Dermal Fillers",
    description: "Monophasic cross-linked HA filler for fine lines and superficial correction.",
    howToUse: "Inject into the superficial-mid dermis using linear threading or serial puncture.",
    safetyInfo: "Aspirate before injection. Avoid injection into blood vessels.",
    prescriptionRequired: false,
    prescriptionType: "optional",
    buyingPrice: 30,
    sellingPrice: 65,
    price: 65,
    unitPrice: 65,
    stock: 35,
    sku: "YVO-CLS-1ML",
    supplier: "LG Life Sciences",
    dispensedBy: "Trained Practitioner",
    sideEffects: ["Bruising", "Redness", "Temporary asymmetry"],
  },
  {
    name: "SkinMedica TNS Recovery Complex 28ml",
    brand: "SkinMedica",
    category: "Skincare",
    description: "Growth factor-rich serum for fine lines, texture, and overall skin rejuvenation.",
    howToUse: "Apply pea-sized amount to clean face morning and evening. Follow with SPF in AM.",
    safetyInfo: "Avoid eyes. Discontinue if irritation occurs.",
    prescriptionRequired: false,
    prescriptionType: "none",
    buyingPrice: 55,
    sellingPrice: 95,
    price: 95,
    unitPrice: 95,
    stock: 25,
    sku: "SKIN-TNS-28ML",
    supplier: "SkinMedica",
    dispensedBy: "Any",
    sideEffects: ["Mild tingling on first use"],
  },
  {
    name: "Cannula 25G x 50mm (Pack of 20)",
    brand: "Softfil",
    category: "Consumables",
    description: "Blunt tip micro-cannula for safer dermal filler injection with reduced bruising risk.",
    howToUse: "Use with an entry needle to create an insertion point. Fan technique recommended.",
    safetyInfo: "Single use only. Dispose in sharps bin.",
    prescriptionRequired: false,
    prescriptionType: "none",
    buyingPrice: 12,
    sellingPrice: 28,
    price: 28,
    unitPrice: 1.4,
    stock: 200,
    sku: "CAN-25G-50MM",
    supplier: "Softfil",
    dispensedBy: "Any Professional",
    sideEffects: [],
  },
  {
    name: "Hyaluronidase 1500 IU",
    brand: "Vitrase",
    category: "Injectables",
    subCategory: "HA Fillers",
    description: "Enzyme for dissolving hyaluronic acid fillers in vascular occlusion emergencies or correction.",
    howToUse: "Reconstitute with saline. Inject into affected area. Repeat every 30 min as needed.",
    safetyInfo: "Emergency use for vascular occlusion. Keep as part of emergency kit.",
    prescriptionRequired: true,
    prescriptionType: "required",
    buyingPrice: 30,
    sellingPrice: 70,
    price: 70,
    unitPrice: 70,
    stock: 40,
    sku: "HYAL-1500IU",
    supplier: "Vitrase UK",
    dispensedBy: "Registered Prescriber",
    sideEffects: ["Localised swelling", "Allergic reaction (rare)"],
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    let inserted = 0;
    let skipped  = 0;

    for (const med of MEDICINES) {
      const exists = await Medicine.findOne({ sku: med.sku });
      if (exists) {
        console.log(`⏭  Skipped (already exists): ${med.name}`);
        skipped++;
      } else {
        await Medicine.create({
          ...med,
          expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000 * 2), // 2 years from now
        });
        console.log(`✅ Inserted: ${med.name}`);
        inserted++;
      }
    }

    console.log(`\n🎉 Seed complete — ${inserted} inserted, ${skipped} skipped.`);
  } catch (err) {
    console.error("❌ Seed failed:", err.message);
  } finally {
    await mongoose.disconnect();
  }
}

seed();
